FROM python:3.9

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --upgrade -r /code/requirements.txt

COPY ./vendor /code/vendor
COPY ./requirement-subtranslator.txt /code/requirement-subtranslator.txt
RUN pip install --upgrade -r /code/requirement-subtranslator.txt

COPY ./app /code/app

COPY ./data/language_pairs.json /code/data/language_pairs.json

ENV USE_GPU=false

CMD ["fastapi", "run", "app/main.py", "--port", "80", "--workers", "8"]